name = "note-system"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-21"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NOTES_CACHE"
id = "PLACEHOLDER_KV_NAMESPACE_ID"

[vars]
GITHUB_OWNER = "MixGeeker"
GITHUB_REPO = "venezuela_note"
